# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Play_24X7' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Play_24X7

pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
end
